= BasicAngularForm

==== step 1:
install angular, following the instructions I found on this site:
https://www.npmjs.com/package/@angular/cli/v/10.1.7

- I clone this exercise on my computer
- I checked if I have npm installed by typing "npm -v" (or "npm -version") in the terminal.
- I installed Angular Globally cli (command line interface) with "npm install -g @angular/cli" and checked afterwards
whether it was installed with the command "ng version".
- I go to my exercise in the terminal and create a new project( friendsBook): "ng new friendsBook"
- I go in the terminale inside the "friendsBook" folder and run the command ng serve --port 4500.
- Now I can check out my angular app on localhost:4500.

- In PhpStorm I can navigate to project-name/src/app, and find 2 files who prepare the webpage together.
        1. The template: "app.component.html"
        2. The component: "app.component.ts"

(The view you see in the page is produced by the combination of that template and the component that brings the logic to the template.)

Before we actually start, we make the app.component.html empty.

Inside the AppComponent class (in app.component.ts) we'll write the logic,
and in the template (app.component.html) we write the html.

==== EXERCISE

In the HTML file, I add a form with the required inputs:
 1. First name
 2. Last name
 3. Email
 4. Phone number
 5. Favourite language (html, css, js, php, ...), this will be a select with options

I don't get it at all, so I 'll see some more of the tutorial first.

In html, I created, the input fields, then I made the array of the languages in 'class FormComponent of the form.components.ts'.
Then I create a ngFor-loop in the option of the select box.

 <option *ngFor="let language of languages">{{language}}</option>

NOTE:   to show the whole array on the page (to check), you can use {{languages | json}}