= BasicAngularForm

== step 1:
install angular, following the instructions I found on this site:
https://www.npmjs.com/package/@angular/cli/v/10.1.7

- I clone this exercise on my computer
- I checked if I have npm installed by typing "npm -v" (or "npm -version") in the terminal.
- I installed Angular Globally cli (command line interface) with "npm install -g @angular/cli" and checked afterwards
whether it was installed with the command "ng version".
- I go to my exercise in the terminal and create a new project( friendsBook): "ng new friendsBook"
- I go in the terminale inside the "friendsBook" folder and run the command ng serve --port 4500.
- Now I can check out my angular app on localhost:4500.

- In PhpStorm I can navigate to project-name/src/app, and find 2 files who prepare the webpage together.
        1. The template: "app.component.html"
        2. The component: "app.component.ts"

(The view you see in the page is produced by the combination of that template and the component that brings the logic to the template.)

Before we actually start, we make the app.component.html empty.

Inside the AppComponent class (in app.component.ts) we'll write the logic,
and in the template (app.component.html) we write the html.

== EXERCISE

. In the HTML file, I add a form with the required inputs:
    - First name
    - Last name
    - Email
    - Phone number
    - Favourite language (html, css, js, php, ...), this will be a select with options

I don't get it at all, so I 'll see some more of the tutorial first.

[start=2]
. In html, I created, the input fields, then I made the array of the languages in 'class FormComponent of the form.components.ts'. (instruction 9)
. Then I create a ngFor-loop in the option of the select box.

 <option *ngFor="let language of languages">{{language}}</option>

NOTE:   to show the whole array on the page (to check), you can use {{languages | json}}

[start=4]
. Now I have to connect the html form with angular. (instruction 10 & 11)
https://angular.io/guide/forms
https://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/

*In the app.module.ts*,  I import the FormsModule from @angular/forms,
by adding 'FormsModule' in the 'imports: [] array in @NgModule({}).
For more flexibility, I also insert

[source,angularjs]

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { FormComponent } from '../components/form/form.component';
import {FormsModule, ReactiveFormsModule} from "@angular/forms";

[source,angularjs]
@NgModule({
 declarations: [
 AppComponent,
 FormComponent,
],
imports: [
 BrowserModule,
 FormsModule,
 ReactiveFormsModule],
 providers: [],
 bootstrap: [AppComponent]
})
export class AppModule { }


I create a variable 'FriendsForm' *in form.components.ts*,  which will be linked on HTML.

[source,angularjs]

export class FormComponent implements OnInit {
  languages: string[] = ['html', 'css', 'javaScript', 'php', 'typeScript'];

  friendsForm = new FormGroup({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    email: new FormControl('', Validators.required),
    phone: new FormControl(''),
    favouritLanguage: new FormControl(''),
  });


In stead of '#formName="ngForm" ', I added ' [formGroup]="friendsForm" ' to the (html) form to create
two-way data bindings for reading and writing input-control values.
(Reactive Forms scale better and support better more advanced use cases. Reactive Forms also promote a clearer separation
between business logic and presentation logic, which leads to clearer, easier to read and more maintainable HTML templates)

each input needs te be connected

[source,angular2html]
<form [formGroup]="friendsForm">
  <label>First name:</label><br>
  <input type="text" formControlName="firstName"><br><br>
  <label>Last name:</label><br>
  <input type ="text" formControlName="lastName"><br><br>
  <label>Email:</label><br>
  <input type="text" formControlName="email"><br><br>
  <label>Phone number:</label><br>
  <input type="text" formControlName="phone"><br><br>
  <label>Favourite language:</label><br>
  <select formControlName="favouriteLanguage">
    <option *ngFor="let language of languages" [value]="language">{{language}}</option>
  </select>

[start=5]
. Next step is to display when a field is invalid to the user.(instruction 12)
https://angular.io/guide/form-validation

In a reactive form, the source of truth is the component class. Instead of adding validators through attributes in the template,
you add validator functions directly to the form control model in the component class.
Angular then calls these functions whenever the value of the control changes.



In the form.component.ts, I created a function (showInvalid), which return a boolean and make it possible to
pass an invalid statement to the form elements.

In the Friendsform (form.component.ts, class FormComponent), I add the validators
 - firstName and lastname: validators.patters(...)       https://angular.io/api/forms/PatternValidator
 - email: validators.email
 - phone: validators.patters(...)  https://regex101.com/library/hN5oL4


In the css (form.component.css), I pass the formatting for invalid fields (red border)

in the form of the html, I added to each input ' [class.invalid]="showInvalid('name inputlield') '.
(The class only appears if the boolean is true)

[start=6]
. If all the fields are valid, the forms valid property will also be set to valid (instruction 13)

[source, angular2html]
  <input type="submit" value="Submit" [disabled]="!friendsForm.valid">

[start=7]
. next step is to submit data to the server (instruction 14)
I read these instructions, but did not understand what they are talking about https://angular.io/api/forms/NgForm#description
So I needed some more explanation...

 - By adding the ngSubmit property to the form (in form.component.html), I can bind a function (addFriend) to it and use that function in the
component class to trigger it on submit

[source,angular2html]
<form [formGroup]="friendsForm" (ngSubmit)="addFriend()">

 - The function needs to be made in the class FormComponent (form.components.ts).

[source,angularjs]
  addFriend() {
    console.log('add friend');
    const friend: Friend = new Friend(
      this.friendsForm.get('firstName')?.value,
      this.friendsForm.get('lastName')?.value,
      this.friendsForm.get('email')?.value,
      this.friendsForm.get('phone')?.value,
      this.friendsForm.get('favouriteLanguage')?.value,
    );
    this.addFriendService.addFriend(friend);
  }

 - Now I first created a map services and then made a service to add this friend to the friendlist server.
Using the cli for this and input the command 'ng g s addFriend' ( a"ng"ular "g"enerate "s"ervice with name "addFriend").

Note: when you generate a service you'll see that after the name you've given it will automatically add "Service" after it.
 In this service, I create an addFriend service

[source,angularjs]

import {HttpClient} from "@angular/common/http";

[source,angularjs]
export class AddFriendService {
  constructor(private http: HttpClient) { }
}

 - The HttpClientModule needs to be imported in the app.module.ts, and also be added it to the imports array below.

[start=8]
. Making an http request to post the data to a server... (instruction 15)

 - I import friend into the form.component.ts

[source,angularjs]
import {Friend} from "../../app/models/friend";


 - In the service, I create a method 'addFriend, with parameter friend and a post request and make a property 'url'
https://angular.io/guide/observables

[source,angularjs]
  addFriend(friend: any) {
    this.http.post(url, friend).subscribe(res => {});
  }

 - The service needs to be imported in the form.component.ts and needs a constructor.

[source,angularjs]
  constructor(private addFriendService: AddFriendService) {
  }

[start=9]
.Now everything is set up, we need to send our data to the local API. (instruction 16)

 - In 'add-friends.service.ts', I set the port to 9000 (const url: string = 'http://localhost:9000/;) and check if it works by
running the command 'node server' in the server folder of the terminal and navigate to localhost:9000/.
- In server.js there is an array allFriends. We need to push the 'new friends' to this array.
 I make a get function and a post function, so the server.js looks like:

[source,angularjs]
let allFriends = [{fName: 'Coach', lName: 'Tim', email: 'tim.broos@becode.org', phone: '0469420666', signatureMove: 'Yeet', language: 'Javascript'}];

app.get('/', function (request, response) {
response.send('Hello from server');
});

app.get('/allFriends', function (request, response) {
response.send(allFriends);
});

app.post('/addFriend', function (request, response) {
console.log('addFriend', request.body);
allFriends.push(
{
fName: request.body.firstName,
lName: request.body.lastName,
email: request.body.email,
phone: request.body.phone,
language: request.body.favouriteLanguage
}
);
response.send(allFriends);
});


[start=10]
. The get request also needs to be made (in case we load tha page and when we post data to the server) (instruction 17)
https://angular.io/guide/http

 - I renamed the (class) addFriendService to  FriendService (friend.service.ts) and mad a method 'getFriend' to return the http (This method returns an observable)

[source,angularjs]
  getFriends(): Observable<any> {
    return this.http.get(urlget);
  }

This method needs to be called on load (onInit) and when we add a friend.
In form.component.ts, I create an variable allfriends$ ('the $ sign, makes it clear that this is an observable https://angular.io/guide/rx-library#naming-conventions-for-observables)


[source,angularjs]
  allFriends$: Observable<any>;
[source,angularjs]
ngOnInit(): void {
    this.allFriends$ = this.friendService.getFriends();
  }
[source,angularjs]
addFriend() {
console.log('add friend');
const friend: Friend = new Friend(
this.friendsForm.get('firstName')?.value,
this.friendsForm.get('lastName')?.value,
this.friendsForm.get('email')?.value,
this.friendsForm.get('phone')?.value,
this.friendsForm.get('favouriteLanguage')?.value,
);
this.friendService.addFriend(friend);
this.allFriends$ = this.friendService.getFriends();
}

- to check if it works, I call the object in the html

[source,angular2html]
{{allFriends$ | async | json}}

[start=11]
. Next step is showing the friends in the template (instruction 18)
  - I added a div in the html and put the code '<div *ngFor="let friend of allFriends$ | async">' in it.
 note: the async-pipe (| async) will subscribe to the observable in the template.

In this div, we can call and display the properties.

[source,angular2html]
<div *ngFor="let friend of allFriends$ | async">
{{friend.fName}}{{friend.lName}}
{{friend.email}}
{{friend.phone}}
{{friend.language}}
</div>


