= BasicAngularForm

== step 1:
install angular, following the instructions I found on this site:
https://www.npmjs.com/package/@angular/cli/v/10.1.7

- I clone this exercise on my computer
- I checked if I have npm installed by typing "npm -v" (or "npm -version") in the terminal.
- I installed Angular Globally cli (command line interface) with "npm install -g @angular/cli" and checked afterwards
whether it was installed with the command "ng version".
- I go to my exercise in the terminal and create a new project( friendsBook): "ng new friendsBook"
- I go in the terminale inside the "friendsBook" folder and run the command ng serve --port 4500.
- Now I can check out my angular app on localhost:4500.

- In PhpStorm I can navigate to project-name/src/app, and find 2 files who prepare the webpage together.
        1. The template: "app.component.html"
        2. The component: "app.component.ts"

(The view you see in the page is produced by the combination of that template and the component that brings the logic to the template.)

Before we actually start, we make the app.component.html empty.

Inside the AppComponent class (in app.component.ts) we'll write the logic,
and in the template (app.component.html) we write the html.

== EXERCISE

1. In the HTML file, I add a form with the required inputs:
    - First name
    - Last name
    - Email
    - Phone number
    - Favourite language (html, css, js, php, ...), this will be a select with options

I don't get it at all, so I 'll see some more of the tutorial first.

[start=2]
2. In html, I created, the input fields, then I made the array of the languages in 'class FormComponent of the form.components.ts'.
3. Then I create a ngFor-loop in the option of the select box.

 <option *ngFor="let language of languages">{{language}}</option>

NOTE:   to show the whole array on the page (to check), you can use {{languages | json}}

[start=4]
4. Now I have to connect the html form with angular.
https://angular.io/guide/forms
https://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/

*In the app.module.ts*,  I import the FormsModule from @angular/forms,
by adding 'FormsModule' in the 'imports: [] array in @NgModule({}).
For more flexibility, I also insert

[source,typescript]

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { FormComponent } from '../components/form/form.component';
import {FormsModule, ReactiveFormsModule} from "@angular/forms";

[source,typescript]
@NgModule({
 declarations: [
 AppComponent,
 FormComponent,
],
imports: [
 BrowserModule,
 FormsModule,
 ReactiveFormsModule],
 providers: [],
 bootstrap: [AppComponent]
})
export class AppModule { }

*in form.components.ts*, I create a variable 'FriendsForm', which will be linked on HTML.

[source,typescript]

export class FormComponent implements OnInit {
  languages: string[] = ['html', 'css', 'javaScript', 'php', 'typeScript'];

  friendsForm = new FormGroup({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    email: new FormControl('', Validators.required),
    phone: new FormControl(''),
    favouritLanguage: new FormControl(''),
  });


In stead of '#formName="ngForm" ', I added ' [formGroup]="friendsForm" ' to the (html) form to create
two-way data bindings for reading and writing input-control values.
(Reactive Forms scale better and support better more advanced use cases. Reactive Forms also promote a clearer separation
between business logic and presentation logic, which leads to clearer, easier to read and more maintainable HTML templates)

each input needs te be connected

[source,html]
<form [formGroup]="friendsForm">
  <label>First name:</label><br>
  <input type="text" formControlName="firstName"><br><br>
  <label>Last name:</label><br>
  <input type ="text" formControlName="lastName"><br><br>
  <label>Email:</label><br>
  <input type="text" formControlName="email"><br><br>
  <label>Phone number:</label><br>
  <input type="text" formControlName="phone"><br><br>
  <label>Favourite language:</label><br>
  <select formControlName="favouriteLanguage">
    <option *ngFor="let language of languages" [value]="language">{{language}}</option>
  </select>


